[build]
builder = "nixpacks"

[build.nixpacks]
aptPkgs = ["libgomp1"]

[deploy]
startCommand = "gunicorn app:app --bind 0.0.0.0:$PORT"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

